import { Geist, Geist_Mono } from "next/font/google";
import Header from "./component/header";
import Footer from "./component/footer";
import 'bootstrap/dist/css/bootstrap.css'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Baskervville:ital@0;1&display=swap" rel="stylesheet"/>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Header/>
        {children}
        <Footer/>

      </body>
    </html>
  );
}
